version: '3.9'

services:
  database:
    container_name: my_library_helper
    image: 'postgres:16'
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: arty
      POSTGRES_PASSWORD: arty
    ports:
      - '5444:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: